services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=super_root
            - POSTGRES_PASSWORD=P@sSWord
            - POSTGRES_DB=bobank
        ports:
            - '39004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './deployment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '39000:80'

    php-fpm:
        build: deployment/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './deployment/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './deployment/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
